FROM nginx:1.27.0-alpine

# Copy pre-built files from local build
COPY build /usr/share/nginx/html
COPY .env.example /usr/share/nginx/html/.env
COPY nginx-custom.conf /etc/nginx/conf.d/default.conf

RUN apk add --update nodejs npm
RUN npm i -g runtime-env-cra

WORKDIR /usr/share/nginx/html
EXPOSE 3000

CMD ["/bin/sh", "-c", "runtime-env-cra && nginx -g \"daemon off;\""]
